### ISSUE TITLE
Downloading options data from the ASX

### ISSUE THREAD

**Issue by JoeFernando** [DataWookie/flipsideR#1]
Hi Andrew,

Could you spare a bit of your time to also include ASX options data.

The main options data page is:
http://www.asx.com.au/asx/markets/optionPrices.do

Individual options details derived from:
http://www.asx.com.au/asx/markets/optionPrices.do?by=underlyingCode&underlyingCode=ozl&expiryDate=&optionType=B

just by changing the the underlying code, in the above example "ozl", you can generate the same data for other securities as well.

The most active options in the ASX are:
CBA
NAB
WBC
BHP
RIO

Thanks in advnace.

Kind regards,
Joe

**Comment by datawookie** [comment]
Hi Joe,

I've added the capability to download ASX options. Just specify "ASX" as the exchange parameter to getOptionChain().

Regards,
Andrew.
